# Generated by Django 3.2.5 on 2023-06-09 07:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import helper
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='category/', validators=[helper.file_size])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('selling_price', models.BigIntegerField()),
                ('offering_price', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='product/', validators=[helper.file_size])),
                ('img_second', models.ImageField(blank=True, upload_to='product/', validators=[helper.file_size])),
                ('img_third', models.ImageField(blank=True, upload_to='product/', validators=[helper.file_size])),
                ('img_forth', models.ImageField(blank=True, upload_to='product/', validators=[helper.file_size])),
                ('img_fifth', models.ImageField(blank=True, upload_to='product/', validators=[helper.file_size])),
                ('video', models.URLField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('slug', models.SlugField(max_length=500, null=True, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_catgeory', to='product.category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_subcatgeory', to='product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(blank=True, choices=[('Color', 'Color'), ('Size', 'Size')], default='Color', max_length=100)),
                ('variation_value', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='product.product')),
            ],
        ),
    ]
